theme: jekyll-theme-minimal
title: "Pavan's profile"
description: ""
gem "github-pages", group: :jekyll_plugins
# logo: file.png
# show_downloads: true
github:
  is_user_page: true
name: "S. Pavankumar Dubagunta"
designation: "Staff AI Scientist"
organization: "Uniphore Software Systems"
email: "dspavankumar@gmail.com"
address: "Bengaluru, India"
