theme: jekyll-theme-minimal
title: "Pavan's profile"
description: ""
gem "github-pages", group: :jekyll_plugins
# logo: file.png
# show_downloads: true
github:
  is_user_page: true
name: "S. Pavankumar Dubagunta"
designation: "Applied Scientist II"
organization: "Amazon Development Centre"
email: "dspavankumar@gmail.com"
address: "Bengaluru, India"
